#' Filter search result and keep only people
#'
#' @param search A data frame generated by `tw_search()`, or a search query. If a data frame is given, language and limits are ignore.
#' @param p A character vector of length 1, a property. Must always start with the capital letter "P", e.g. "P31" for "instance of".
#' @param q A character vector of length 1, a wikidata id. Must always start with the capital letter "Q", e.g. "Q5" for "human being".
#' @param language Language to be used for the search.
#' @param limit Maximum numbers of responses to be given.
#'
#' @return A data frame with three columns, `id`, `label`, and `description`, filtered by the above criteria.
#' @export
#'
#' @examples
#'
#' \dontrun{
#' tw_search("Antonio Vivaldi") %>%
#'   tw_filter()
#' }
#'
tw_filter <- function(search,
                      p,
                      q,
                      language = "en",
                      limit = 10) {
  if (is.data.frame(search) == TRUE) {
    search_result <- search
  } else if (length(search) > 1) {
    usethis::ui_stop("Input must be a single query or a data frame generated by `tw_search_wiki()`")
  } else if (is.character(search) == TRUE) {
    search_result <- tidywikidatar::tw_search_wiki(
      search = search,
      language = language,
      limit = limit
    )
  }
  person_id <- purrr::map_dfr(
    .x = search_result$id[2],
    .f =
      function(current_id) {
        current_wiki <- tidywikidatar::tw_get(id = current_id)

        current_value <- current_wiki %>%
          dplyr::filter(property == p) %>%
          dplyr::pull(value)

        if (is.null(current_value)) {
          tibble::tibble(id = as.character("NA"))
        } else if (current_value == q) {
          tibble::tibble(id = current_id)
        } else {
          tibble::tibble(id = as.character("NA"))
        }
      }
  ) %>%
    tidyr::drop_na()

  search_result %>%
    dplyr::semi_join(y = person_id,
                     by = "id")
}


#' Filter search result and keep only people
#'
#' A wrapper of `tw_filter()` that defaults to keep only "instance of" (P31) "human being" (Q5).
#'
#' @param search A data frame generated by `tw_search()`, or a search query. If a data frame is given, language and limits are ignore.
#' @param language Language to be used for the search.
#' @param limit Maximum numbers of responses to be given.
#'
#' @return A data frame with three columns, `id`, `label`, and `description`; all rows refer to a human being.
#' @export
#'
#' @examples
#'
#' \dontrun{
#' tw_search("Antonio Vivaldi") %>%
#'   tw_filter_people()
#' }
#'
#'
tw_filter_people <- function(search,
                             language = "en",
                             limit = 10) {
  tidywikidatar::tw_filter(search = search,
                           p = "P31",
                           q = "Q5",
                           language = language,
                           limit = 10)
}

